name: zenlook
description: "aplikasi seperti zenly"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.1
  flutter_local_notifications: ^19.0.0
  geolocator: ^14.0.3
  image_picker: ^1.1.2
  intl: ^0.20.3
  latlong2: 0.9.1
  path_provider: ^2.1.5
  permission_handler: ^13.0.0
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.17.1
  uuid: ^4.6.0
  http: ^1.2.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  record: ^6.1.2
  audioplayers: ^6.1.0
  file_picker: ^12.2.0
  just_audio: ^0.9.46
  audio_service: ^0.18.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "assets/icon2.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  image_path: "assets/icon2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon2.png"
  adaptive_icon_foreground_inset: 11

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon2.png
    - .env
